Follow Pastebin links module.
InQuest/ThreatIngestor pull request #102
Opened 2020-10-30 23:16 UTC by RatherBland

Added module to follow and extract IOC's from Pastebin links embedded in tweets as per issue #97 
This works very similarly to the Twitter module and goes off of search, lists, users, etc.

I also updated the Twitter module to support `list_id` as not all lists have an associated slug.
https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/create-manage-lists/api-reference/get-lists-statuses

2020-10-31 02:56 UTC, cmmorrow commented on threatingestor/sources/twitter_follow_links.py
> +import re
```suggestion
import re
import requests

import twitter
from loguru import logger

from threatingestor.sources import Source
```

2020-10-31 02:57 UTC, cmmorrow commented on threatingestor/sources/twitter_follow_links.py
> +import re
Changing import order to Google style, similar to other modules in the project.

2020-10-31 03:12 UTC, cmmorrow commented on threatingestor/sources/twitter_follow_links.py
> +                        # print(url['expanded_url'])
You can remove these commented-out lines if you don't intend for them to run.

2020-10-31 03:16 UTC, cmmorrow commented on threatingestor/sources/twitter_follow_links.py
> +        return saved_state, artifacts
I don't see where you set `saved_state`. For example, `twitter.py` has `saved_state = tweet['id']`.

2020-10-31 03:43 UTC, cmmorrow requested changes
Thanks for the PR @RatherBland! Please see my comments below. Once resolved, I'll merge your changes and prepare the next ThreatIngestor release.

2020-11-02 23:02 UTC, RatherBland commented
Thanks for the feedback @cmmorrow I believe my updates have met your requested changes.

Cheers!

2020-11-03 21:04 UTC, cmmorrow approved these changes
Thanks for working on this @RatherBland! I'll approve and merge your code changes and include it in the next release of ThreatIngestor.

2020-11-03 21:05 UTC, merged